apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;

      location /static/ {
          root /app;
          autoindex on;
      }

      location /media/ {
          root /app;
          autoindex on;
      }
    
      location / {
          proxy_pass http://lottery-service:8000;
          proxy_set_header Host $host;
          proxy_set_header X-Real_IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
    }