# Generated by Django 5.1.5 on 2025-02-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=2)),
                ('times', models.IntegerField()),
            ],
        ),
    ]
