apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      serviceAccountName: ann-service
      imagePullSecrets:
        - name: gcr-secret
      containers:
        - name: celery-beat
          image: asia-east1-docker.pkg.dev/ann-project-390401/ann-repo/lottery:latest
          command: ["celery", "-A", "lottery", "beat", "--loglevel=info"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"  # Replace with RabbitMQ service name
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASS
              value: "guest"