apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      serviceAccountName: ann-service
      containers:
        - name: celery-worker
          image: asia-east1-docker.pkg.dev/ann-project-390401/ann-repo/lottery:v1
          command: ["celery", "-A", "lottery", "worker", "-Q", "lonquery_pq", "--loglevel=info"]
          resources:
            requests:
              memory: "128Mi"  # Minimum memory required
              cpu: "100m"      # Minimum CPU required
            limits:
              memory: "256Mi"  # Maximum memory allowed
              cpu: "250m"      # Maximum CPU allowed
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"  # Replace with RabbitMQ service name
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASS
              value: "guest"