apiVersion: apps/v1
kind: Deployment
metadata:
  name: lottery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lottery
  template:
    metadata:
      labels:
        app: lottery
    spec:
      serviceAccountName: ann-service
      containers:
        - name: lottery
          image: asia-east1-docker.pkg.dev/ann-project-390401/ann-repo/lottery:v1
          ports:
          - containerPort: 8000
          volumeMounts:
            - name: static-files
              mountPath: /app/staticfiles
          resources:
            requests:
              memory: "128Mi" 
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: GCP_PROJECT_ID
              value: "ann-project-ann-project-390401"
            - name: ENV
              value: "develop"
      volumes:
        - name: static-files
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lottery-service
spec:
  selector:
    app: lottery
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000