apiVersion: apps/v1
kind: Deployment
metadata:
  name: lottery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lottery
  template:
    metadata:
      labels:
        app: lottery
    spec:
      containers:
        - name: lottery
          image: asia-east1-docker.pkg.dev/ann-project-390401/ann-repo/lottery:latest
          ports:
          - containerPort: 8000
          volumeMounts:
            - name: static-files
              mountPath: /app/staticfiles
          resources:
            requests:
              memory: "512Mi" 
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: GCP_PROJECT_ID
              value: "ann-project-ann-project-390401"
            - name: ENV
              value: "develop"
    volumes:
      - name: static-files
        emptyDir: {}
---
apiVersion: apps/v1
kind: Service
metadata:
  name: lottery-service
spec:
  selector:
    app: lottery
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000